config/routes.rb
Rails.application.routes.draw do
  get '/login' => "sessions#new", as: :login
  post '/login' => "sessions#create"
  delete '/login' => "sessions#destroy"

  resources :links

  get '/links/:title/comments' => "comments#index", as: :comments
  post '/links/:title/comments' => "comments#create"

  get '/links/:title/new' => "comments#new", as: :new_comment

  resources :users, only: [:new, :create]

  root 'links#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :link
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  
  validates :url, format: {with: /\A(http|https):\/\//}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :links
  validates :email, format: {with: /@/} , uniqueness: true

  def self.sign_up(email)
    User.create(email: email)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  helper_method :current_user
  def current_user
    @current_user ||= User.find_by(session[:user_id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @links = Link.all
    @current_post = Link.find_by(title: params["title"])
    @comments = @current_post.comments
  end

  def new
    # unless current_user
    #   redirect_to "/"
    #   return
    # end
    @new_comment = Comment.new
  end

  def create

    @current_link = Link.find_by(title: params["title"])

    @current_comment = Comment.create(body: params["comment"]["body"])
    @current_comment.update(link_id: @current_link.id)

    redirect_to "/links/#{@current_link.title}/comments"
  end

  private def comment_params
    params.require("comment").permit(:body, :link_id)
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  def index
    @links = Link.all
  end

  def show
    @link = Link.find(params["id"])
  end

  def new
    unless current_user
      render :you_must_login_to_post_links
      return
    end
    @new_link = Link.new

    # redirect_to "/links"
  end

  def create
    @link = Link.create(link_params)
    @link.update(vote_count: 0)

    redirect_to "/links/#{@link.id}"
  end

  private def link_params
    params.require("link").permit(:title, :url, :vote_count)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params["user"]["email"])

    if @user
      session[:user_id] = @user.id
      binding.pry
      redirect_to "/login"
    else
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to "/login"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.sign_up(params["user"]["email"])
    @user.update(name: params["user"]["name"])

    if @user.valid?
      redirect_to (links_path)
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/index.html.erb
<h1>You are now viewing the comments for <%= @current_post.title %></h1>


<table class="table table-striped">
  <thead>
    <tr>
      <th>
        Comment
      </th>
    </tr>
  </thead>
  <tbody>
    <% @comments.each do |cmnt| %>
    <tr>
      <td>
      <%= cmnt.body %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "create new comment", "/links/#{@current_post.title}/new" %> <br>
<%= link_to "go back to all links", links_path %>

app/views/comments/new.html.erb
<h1>new comment page</h1>

<%= form_for @new_comment, url: comments_path do |f|  %>
<%= f.label :body %>
<%= f.text_field :body %>

<%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!-- ask russell about viewing current webpage -->
<!DOCTYPE html>
<html>
<head>
  <title>RedditApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <main>
    <%# binding.pry %>
    <% if current_user %>

    <%= current_user.email %> is currently logged in.  Not you?
    <%= link_to "Log out", login_path, method: :delete %>

    <% else %>

    <%= link_to "Sign_up", new_user_path %>
    <%= link_to "Login", login_path %>

    <% end %>

    <%= yield %>
    <pre>
      <code>
        Current User ID = <%= session[:user_id] %>
        <%= current_user.inspect %>
      </code>
    </pre>

  </main>
</body>
</html>

app/views/links/index.html.erb
<h1>These are all the links</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>
        Post
      </th>
      <th>
        Comments
      </th>
      <th>
        Submitted by
      </th>
    </tr>
  </thead>
  <tbody>
    <% @links.each do |link| %>
    <tr>
      <td>
        <%# @links.vote_count %>
      </td>
      <td>
        <a href="<%= link.url %>">  <%= link.title %></a>
      </td>
      <td>
        <a href="/links/<%= link.title %>/comments">  <%= link.title %> comments</a>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Submit new link", new_link_path %>

app/views/links/new.html.erb
<h1>This is where you create a new link</h1>


<%= form_for @new_link do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>

<%= f.label :url %>
<%= f.text_field :url %>

<%= f.submit "submit link" %>
<% end %>

app/views/links/show.html.erb
<h1>Here is <a target="_blank" href="<%= @link.url %>"><%= @link.title %></a></h1>

<%= link_to "Back to links", links_path %>

app/views/links/you_must_login_to_post_links.html.erb
<h1>Unfortunately, you must login to post links.</h1>

app/views/users/new.html.erb
<h1>Welcome to the login page</h1>


<%= form_for @user, url: users_path do |f|%>

  <% @user.errors.full_messages.each do |msg| %>
  <p>
  <%= msg %>
  </p>

<% end %>

<%= f.label :email %>
<%= f.email_field :email %>

<%= f.label :name   %>
<%= f.text_field :name  %>

<%= f.submit %>
<% end %>